
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'nand_phy.ucf'
####################################################################################

#Anomalies in pin assignment
# Each CHIP has shared WE#/NAND_CLK (probably a bad choice but too late)
# For CE#, [0, 2, 4, 6..] on the schematic correponds to Bus_N_0
# CE#, [1, 3, 5, 7..] on the schematic correponds to Bus_N_1


####################################################
#Clock in and reset
####################################################
set_property PACKAGE_PIN E5 [get_ports CLK_sysClkP]
# /home/mingliu/NandController/src/nand_phy.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK_sysClkP' has been applied to the port object 'CLK_sysClkP'.
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkP]
set_property PACKAGE_PIN D5 [get_ports CLK_sysClkN]
# /home/mingliu/NandController/src/nand_phy.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK_sysClkN' has been applied to the port object 'CLK_sysClkN'.
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkN]
#set_property PACKAGE_PIN P14 [get_ports RST_N_sysRstn]
# /home/mingliu/NandController/src/nand_phy.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RST_N_sysRstn' has been applied to the port object 'RST_N_sysRstn'.
#set_property IOSTANDARD LVCMOS18 [get_ports RST_N_sysRstn]


#Clock constraint

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# /home/mingliu/NandController/src/nand_phy.ucf:20
create_clock -name CLK_sysClkP -period 10.000 [get_ports CLK_sysClkP]
set_input_jitter CLK_sysClkP 0.100



####################################################
# Bus 0 Pins
####################################################

# Bus 0_shared. For now name them B_0_0_*
set_property PACKAGE_PIN E6 [get_ports {B_SHARED_0_WEN_NCLK[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:29
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_0_WEN_NCLK[0]' has been applied to the port object 'B_SHARED_0_WEN_NCLK[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_0_WEN_NCLK[0]}]
set_property PACKAGE_PIN H8 [get_ports {B_SHARED_0_WEN_NCLK[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:30
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_0_WEN_NCLK[1]' has been applied to the port object 'B_SHARED_0_WEN_NCLK[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_0_WEN_NCLK[1]}]
set_property PACKAGE_PIN H7 [get_ports {B_SHARED_0_WEN_NCLK[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:31
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_0_WEN_NCLK[2]' has been applied to the port object 'B_SHARED_0_WEN_NCLK[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_0_WEN_NCLK[2]}]
set_property PACKAGE_PIN F8 [get_ports {B_SHARED_0_WEN_NCLK[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:32
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_0_WEN_NCLK[3]' has been applied to the port object 'B_SHARED_0_WEN_NCLK[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_0_WEN_NCLK[3]}]
#NET "B_0_1_DEBUG0[0]" LOC = K2 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[1]" LOC = L3 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[2]" LOC = J1 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[3]" LOC = K1 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[4]" LOC = M5 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[5]" LOC = M6 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[6]" LOC = N6 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG0[7]" LOC = N7 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[0]" LOC = K5 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[1]" LOC = L5 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[2]" LOC = L4 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[3]" LOC = M4 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[4]" LOC = L7 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[5]" LOC = M7 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[6]" LOC = J3 | IOSTANDARD = LVCMOS18;
#NET "B_0_1_DEBUG1[7]" LOC = K3 | IOSTANDARD = LVCMOS18;

#Bus 0_0
set_property PACKAGE_PIN B5 [get_ports B_0_0_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQS' has been applied to the port object 'B_0_0_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_0_DQS]
set_property PACKAGE_PIN E3 [get_ports {B_0_0_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:52
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[7]' has been applied to the port object 'B_0_0_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[7]}]
set_property PACKAGE_PIN F3 [get_ports {B_0_0_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[6]' has been applied to the port object 'B_0_0_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[6]}]
set_property PACKAGE_PIN C3 [get_ports {B_0_0_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:54
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[5]' has been applied to the port object 'B_0_0_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[5]}]
set_property PACKAGE_PIN D3 [get_ports {B_0_0_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:55
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[4]' has been applied to the port object 'B_0_0_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[4]}]
set_property PACKAGE_PIN A4 [get_ports {B_0_0_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:56
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[3]' has been applied to the port object 'B_0_0_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[3]}]
set_property PACKAGE_PIN B4 [get_ports {B_0_0_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:57
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[2]' has been applied to the port object 'B_0_0_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[2]}]
set_property PACKAGE_PIN C4 [get_ports {B_0_0_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:58
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[1]' has been applied to the port object 'B_0_0_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[1]}]
set_property PACKAGE_PIN D4 [get_ports {B_0_0_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:59
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_0$nandPins_DQ[0]' has been applied to the port object 'B_0_0_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_DQ[0]}]

set_property PACKAGE_PIN G6 [get_ports {B_0_0_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:61
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[7]' has been applied to the port object 'B_0_0_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[7]}]
set_property PACKAGE_PIN G9 [get_ports {B_0_0_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:62
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[6]' has been applied to the port object 'B_0_0_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[6]}]
set_property PACKAGE_PIN J5 [get_ports {B_0_0_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:63
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[5]' has been applied to the port object 'B_0_0_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[5]}]
set_property PACKAGE_PIN K8 [get_ports {B_0_0_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:64
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[4]' has been applied to the port object 'B_0_0_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[4]}]
set_property PACKAGE_PIN H4 [get_ports {B_0_0_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:65
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[3]' has been applied to the port object 'B_0_0_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[3]}]
set_property PACKAGE_PIN K6 [get_ports {B_0_0_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:66
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[2]' has been applied to the port object 'B_0_0_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[2]}]
set_property PACKAGE_PIN F4 [get_ports {B_0_0_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:67
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[1]' has been applied to the port object 'B_0_0_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[1]}]
set_property PACKAGE_PIN F5 [get_ports {B_0_0_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:68
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CEN[0]' has been applied to the port object 'B_0_0_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_0_CEN[0]}]

set_property PACKAGE_PIN M1 [get_ports B_0_0_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:70
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_WPN' has been applied to the port object 'B_0_0_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_0_WPN]
set_property PACKAGE_PIN H2 [get_ports B_0_0_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:71
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_ALE' has been applied to the port object 'B_0_0_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_0_ALE]
set_property PACKAGE_PIN M2 [get_ports B_0_0_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:72
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_CLE' has been applied to the port object 'B_0_0_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_0_CLE]
set_property PACKAGE_PIN N3 [get_ports B_0_0_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:73
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_0_WRN' has been applied to the port object 'B_0_0_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_0_WRN]

#Bus 0_1
set_property PACKAGE_PIN C1 [get_ports B_0_1_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:76
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQS' has been applied to the port object 'B_0_1_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_1_DQS]
set_property PACKAGE_PIN G2 [get_ports {B_0_1_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:77
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[7]' has been applied to the port object 'B_0_1_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[7]}]
set_property PACKAGE_PIN D1 [get_ports {B_0_1_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:78
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[6]' has been applied to the port object 'B_0_1_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[6]}]
set_property PACKAGE_PIN E1 [get_ports {B_0_1_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:79
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[5]' has been applied to the port object 'B_0_1_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[5]}]
set_property PACKAGE_PIN E2 [get_ports {B_0_1_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:80
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[4]' has been applied to the port object 'B_0_1_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[4]}]
set_property PACKAGE_PIN F2 [get_ports {B_0_1_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:81
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[3]' has been applied to the port object 'B_0_1_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[3]}]
set_property PACKAGE_PIN A2 [get_ports {B_0_1_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:82
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[2]' has been applied to the port object 'B_0_1_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[2]}]
set_property PACKAGE_PIN A3 [get_ports {B_0_1_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:83
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[1]' has been applied to the port object 'B_0_1_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[1]}]
set_property PACKAGE_PIN C2 [get_ports {B_0_1_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:84
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_1$nandPins_DQ[0]' has been applied to the port object 'B_0_1_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_DQ[0]}]

set_property PACKAGE_PIN H6 [get_ports {B_0_1_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:86
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[7]' has been applied to the port object 'B_0_1_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[7]}]
set_property PACKAGE_PIN H9 [get_ports {B_0_1_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:87
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[6]' has been applied to the port object 'B_0_1_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[6]}]
set_property PACKAGE_PIN J6 [get_ports {B_0_1_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[5]' has been applied to the port object 'B_0_1_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[5]}]
set_property PACKAGE_PIN L8 [get_ports {B_0_1_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:89
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[4]' has been applied to the port object 'B_0_1_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[4]}]
set_property PACKAGE_PIN J4 [get_ports {B_0_1_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:90
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[3]' has been applied to the port object 'B_0_1_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[3]}]
set_property PACKAGE_PIN K7 [get_ports {B_0_1_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:91
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[2]' has been applied to the port object 'B_0_1_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[2]}]
set_property PACKAGE_PIN G4 [get_ports {B_0_1_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:92
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[1]' has been applied to the port object 'B_0_1_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[1]}]
set_property PACKAGE_PIN G5 [get_ports {B_0_1_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:93
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CEN[0]' has been applied to the port object 'B_0_1_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_0_1_CEN[0]}]

set_property PACKAGE_PIN N1 [get_ports B_0_1_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:95
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_WPN' has been applied to the port object 'B_0_1_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_1_WPN]
set_property PACKAGE_PIN H1 [get_ports B_0_1_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:96
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_ALE' has been applied to the port object 'B_0_1_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_1_ALE]
set_property PACKAGE_PIN L2 [get_ports B_0_1_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:97
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_CLE' has been applied to the port object 'B_0_1_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_1_CLE]
set_property PACKAGE_PIN N2 [get_ports B_0_1_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:98
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_0_1_WRN' has been applied to the port object 'B_0_1_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_0_1_WRN]

####################################################
# Bus 1 Pins
####################################################

# Bus 1_shared. For now name them B_1_0_*
set_property PACKAGE_PIN V1 [get_ports {B_SHARED_1_WEN_NCLK[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:105
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_1_WEN_NCLK[0]' has been applied to the port object 'B_SHARED_1_WEN_NCLK[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_1_WEN_NCLK[0]}]
set_property PACKAGE_PIN W5 [get_ports {B_SHARED_1_WEN_NCLK[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_1_WEN_NCLK[1]' has been applied to the port object 'B_SHARED_1_WEN_NCLK[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_1_WEN_NCLK[1]}]
set_property PACKAGE_PIN V3 [get_ports {B_SHARED_1_WEN_NCLK[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:107
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_1_WEN_NCLK[2]' has been applied to the port object 'B_SHARED_1_WEN_NCLK[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_1_WEN_NCLK[2]}]
set_property PACKAGE_PIN V6 [get_ports {B_SHARED_1_WEN_NCLK[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:108
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_1_WEN_NCLK[3]' has been applied to the port object 'B_SHARED_1_WEN_NCLK[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_1_WEN_NCLK[3]}]


#Bus 1_0
set_property PACKAGE_PIN AD5 [get_ports B_1_0_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:112
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQS' has been applied to the port object 'B_1_0_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_0_DQS]
set_property PACKAGE_PIN AD4 [get_ports {B_1_0_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:113
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[7]' has been applied to the port object 'B_1_0_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[7]}]
set_property PACKAGE_PIN AC4 [get_ports {B_1_0_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:114
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[6]' has been applied to the port object 'B_1_0_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[6]}]
set_property PACKAGE_PIN AF4 [get_ports {B_1_0_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:115
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[5]' has been applied to the port object 'B_1_0_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[5]}]
set_property PACKAGE_PIN AF5 [get_ports {B_1_0_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:116
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[4]' has been applied to the port object 'B_1_0_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[4]}]
set_property PACKAGE_PIN AF3 [get_ports {B_1_0_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:117
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[3]' has been applied to the port object 'B_1_0_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[3]}]
set_property PACKAGE_PIN AE3 [get_ports {B_1_0_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:118
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[2]' has been applied to the port object 'B_1_0_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[2]}]
set_property PACKAGE_PIN AD3 [get_ports {B_1_0_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:119
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[1]' has been applied to the port object 'B_1_0_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[1]}]
set_property PACKAGE_PIN AC3 [get_ports {B_1_0_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:120
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_2$nandPins_DQ[0]' has been applied to the port object 'B_1_0_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_DQ[0]}]

set_property PACKAGE_PIN Y3 [get_ports {B_1_0_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:122
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[7]' has been applied to the port object 'B_1_0_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[7]}]
set_property PACKAGE_PIN V7 [get_ports {B_1_0_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:123
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[6]' has been applied to the port object 'B_1_0_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[6]}]
set_property PACKAGE_PIN AC1 [get_ports {B_1_0_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:124
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[5]' has been applied to the port object 'B_1_0_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[5]}]
set_property PACKAGE_PIN Y1 [get_ports {B_1_0_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:125
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[4]' has been applied to the port object 'B_1_0_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[4]}]
set_property PACKAGE_PIN AE1 [get_ports {B_1_0_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:126
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[3]' has been applied to the port object 'B_1_0_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[3]}]
set_property PACKAGE_PIN AF2 [get_ports {B_1_0_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:127
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[2]' has been applied to the port object 'B_1_0_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[2]}]
set_property PACKAGE_PIN AC2 [get_ports {B_1_0_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:128
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[1]' has been applied to the port object 'B_1_0_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[1]}]
set_property PACKAGE_PIN AA2 [get_ports {B_1_0_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:129
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CEN[0]' has been applied to the port object 'B_1_0_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_0_CEN[0]}]

set_property PACKAGE_PIN U5 [get_ports B_1_0_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:131
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_WPN' has been applied to the port object 'B_1_0_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_0_WPN]
set_property PACKAGE_PIN R8 [get_ports B_1_0_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:132
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_ALE' has been applied to the port object 'B_1_0_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_0_ALE]
set_property PACKAGE_PIN R7 [get_ports B_1_0_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:133
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_CLE' has been applied to the port object 'B_1_0_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_0_CLE]
set_property PACKAGE_PIN T8 [get_ports B_1_0_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:134
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_0_WRN' has been applied to the port object 'B_1_0_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_0_WRN]

#Bus 1_1
set_property PACKAGE_PIN V8 [get_ports B_1_1_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:137
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQS' has been applied to the port object 'B_1_1_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_1_DQS]
set_property PACKAGE_PIN AB6 [get_ports {B_1_1_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:138
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[7]' has been applied to the port object 'B_1_1_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[7]}]
set_property PACKAGE_PIN AA8 [get_ports {B_1_1_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:139
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[6]' has been applied to the port object 'B_1_1_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[6]}]
set_property PACKAGE_PIN Y8 [get_ports {B_1_1_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:140
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[5]' has been applied to the port object 'B_1_1_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[5]}]
set_property PACKAGE_PIN AB5 [get_ports {B_1_1_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:141
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[4]' has been applied to the port object 'B_1_1_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[4]}]
set_property PACKAGE_PIN AA5 [get_ports {B_1_1_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:142
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[3]' has been applied to the port object 'B_1_1_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[3]}]
set_property PACKAGE_PIN Y5 [get_ports {B_1_1_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:143
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[2]' has been applied to the port object 'B_1_1_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[2]}]
set_property PACKAGE_PIN Y6 [get_ports {B_1_1_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:144
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[1]' has been applied to the port object 'B_1_1_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[1]}]
set_property PACKAGE_PIN Y7 [get_ports {B_1_1_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:145
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_3$nandPins_DQ[0]' has been applied to the port object 'B_1_1_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_DQ[0]}]

set_property PACKAGE_PIN W3 [get_ports {B_1_1_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:147
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[7]' has been applied to the port object 'B_1_1_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[7]}]
set_property PACKAGE_PIN U7 [get_ports {B_1_1_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:148
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[6]' has been applied to the port object 'B_1_1_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[6]}]
set_property PACKAGE_PIN AB1 [get_ports {B_1_1_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:149
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[5]' has been applied to the port object 'B_1_1_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[5]}]
set_property PACKAGE_PIN Y2 [get_ports {B_1_1_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:150
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[4]' has been applied to the port object 'B_1_1_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[4]}]
set_property PACKAGE_PIN AD1 [get_ports {B_1_1_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:151
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[3]' has been applied to the port object 'B_1_1_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[3]}]
set_property PACKAGE_PIN AE2 [get_ports {B_1_1_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:152
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[2]' has been applied to the port object 'B_1_1_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[2]}]
set_property PACKAGE_PIN AB2 [get_ports {B_1_1_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:153
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[1]' has been applied to the port object 'B_1_1_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[1]}]
set_property PACKAGE_PIN AA3 [get_ports {B_1_1_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:154
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CEN[0]' has been applied to the port object 'B_1_1_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_1_1_CEN[0]}]

set_property PACKAGE_PIN U6 [get_ports B_1_1_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:156
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_WPN' has been applied to the port object 'B_1_1_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_1_WPN]
set_property PACKAGE_PIN P8 [get_ports B_1_1_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:157
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_ALE' has been applied to the port object 'B_1_1_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_1_ALE]
set_property PACKAGE_PIN R6 [get_ports B_1_1_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:158
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_CLE' has been applied to the port object 'B_1_1_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_1_CLE]
set_property PACKAGE_PIN T7 [get_ports B_1_1_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:159
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_1_1_WRN' has been applied to the port object 'B_1_1_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_1_1_WRN]


####################################################
# Bus 2 Pins
####################################################

# Bus 2_shared. For now name them B_2_0_*
set_property PACKAGE_PIN H14 [get_ports {B_SHARED_2_WEN_NCLK[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:167
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_2_WEN_NCLK[0]' has been applied to the port object 'B_SHARED_2_WEN_NCLK[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_2_WEN_NCLK[0]}]
set_property PACKAGE_PIN G17 [get_ports {B_SHARED_2_WEN_NCLK[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:168
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_2_WEN_NCLK[1]' has been applied to the port object 'B_SHARED_2_WEN_NCLK[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_2_WEN_NCLK[1]}]
set_property PACKAGE_PIN F18 [get_ports {B_SHARED_2_WEN_NCLK[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:169
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_2_WEN_NCLK[2]' has been applied to the port object 'B_SHARED_2_WEN_NCLK[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_2_WEN_NCLK[2]}]
set_property PACKAGE_PIN G15 [get_ports {B_SHARED_2_WEN_NCLK[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:170
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_2_WEN_NCLK[3]' has been applied to the port object 'B_SHARED_2_WEN_NCLK[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_2_WEN_NCLK[3]}]


#Bus 2_0
set_property PACKAGE_PIN B20 [get_ports B_2_0_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:174
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQS' has been applied to the port object 'B_2_0_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_0_DQS]
set_property PACKAGE_PIN D21 [get_ports {B_2_0_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:175
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[7]' has been applied to the port object 'B_2_0_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[7]}]
set_property PACKAGE_PIN E21 [get_ports {B_2_0_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:176
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[6]' has been applied to the port object 'B_2_0_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[6]}]
set_property PACKAGE_PIN A22 [get_ports {B_2_0_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:177
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[5]' has been applied to the port object 'B_2_0_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[5]}]
set_property PACKAGE_PIN B22 [get_ports {B_2_0_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:178
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[4]' has been applied to the port object 'B_2_0_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[4]}]
set_property PACKAGE_PIN B21 [get_ports {B_2_0_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:179
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[3]' has been applied to the port object 'B_2_0_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[3]}]
set_property PACKAGE_PIN C21 [get_ports {B_2_0_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:180
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[2]' has been applied to the port object 'B_2_0_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[2]}]
set_property PACKAGE_PIN D20 [get_ports {B_2_0_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:181
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[1]' has been applied to the port object 'B_2_0_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[1]}]
set_property PACKAGE_PIN E20 [get_ports {B_2_0_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:182
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_4$nandPins_DQ[0]' has been applied to the port object 'B_2_0_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_DQ[0]}]

set_property PACKAGE_PIN F20 [get_ports {B_2_0_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:184
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[7]' has been applied to the port object 'B_2_0_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[7]}]
set_property PACKAGE_PIN G16 [get_ports {B_2_0_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:185
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[6]' has been applied to the port object 'B_2_0_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[6]}]
set_property PACKAGE_PIN B17 [get_ports {B_2_0_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:186
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[5]' has been applied to the port object 'B_2_0_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[5]}]
set_property PACKAGE_PIN D16 [get_ports {B_2_0_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:187
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[4]' has been applied to the port object 'B_2_0_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[4]}]
set_property PACKAGE_PIN A18 [get_ports {B_2_0_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:188
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[3]' has been applied to the port object 'B_2_0_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[3]}]
set_property PACKAGE_PIN A19 [get_ports {B_2_0_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:189
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[2]' has been applied to the port object 'B_2_0_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[2]}]
set_property PACKAGE_PIN E18 [get_ports {B_2_0_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:190
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[1]' has been applied to the port object 'B_2_0_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[1]}]
set_property PACKAGE_PIN C18 [get_ports {B_2_0_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:191
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CEN[0]' has been applied to the port object 'B_2_0_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_0_CEN[0]}]

set_property PACKAGE_PIN J20 [get_ports B_2_0_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:193
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_WPN' has been applied to the port object 'B_2_0_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_0_WPN]
set_property PACKAGE_PIN J18 [get_ports B_2_0_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:194
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_ALE' has been applied to the port object 'B_2_0_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_0_ALE]
set_property PACKAGE_PIN G20 [get_ports B_2_0_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:195
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_CLE' has been applied to the port object 'B_2_0_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_0_CLE]
set_property PACKAGE_PIN K21 [get_ports B_2_0_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:196
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_0_WRN' has been applied to the port object 'B_2_0_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_0_WRN]

#Bus 2_1
set_property PACKAGE_PIN A23 [get_ports B_2_1_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:199
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQS' has been applied to the port object 'B_2_1_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_1_DQS]
set_property PACKAGE_PIN D23 [get_ports {B_2_1_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:200
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[7]' has been applied to the port object 'B_2_1_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[7]}]
set_property PACKAGE_PIN B24 [get_ports {B_2_1_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:201
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[6]' has been applied to the port object 'B_2_1_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[6]}]
set_property PACKAGE_PIN C24 [get_ports {B_2_1_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:202
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[5]' has been applied to the port object 'B_2_1_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[5]}]
set_property PACKAGE_PIN B26 [get_ports {B_2_1_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:203
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[4]' has been applied to the port object 'B_2_1_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[4]}]
set_property PACKAGE_PIN C26 [get_ports {B_2_1_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:204
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[3]' has been applied to the port object 'B_2_1_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[3]}]
set_property PACKAGE_PIN A25 [get_ports {B_2_1_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:205
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[2]' has been applied to the port object 'B_2_1_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[2]}]
set_property PACKAGE_PIN B25 [get_ports {B_2_1_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:206
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[1]' has been applied to the port object 'B_2_1_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[1]}]
set_property PACKAGE_PIN C22 [get_ports {B_2_1_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:207
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_5$nandPins_DQ[0]' has been applied to the port object 'B_2_1_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_DQ[0]}]

set_property PACKAGE_PIN G19 [get_ports {B_2_1_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:209
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[7]' has been applied to the port object 'B_2_1_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[7]}]
set_property PACKAGE_PIN H16 [get_ports {B_2_1_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:210
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[6]' has been applied to the port object 'B_2_1_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[6]}]
set_property PACKAGE_PIN C17 [get_ports {B_2_1_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:211
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[5]' has been applied to the port object 'B_2_1_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[5]}]
set_property PACKAGE_PIN E16 [get_ports {B_2_1_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:212
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[4]' has been applied to the port object 'B_2_1_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[4]}]
set_property PACKAGE_PIN A17 [get_ports {B_2_1_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:213
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[3]' has been applied to the port object 'B_2_1_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[3]}]
set_property PACKAGE_PIN B19 [get_ports {B_2_1_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:214
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[2]' has been applied to the port object 'B_2_1_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[2]}]
set_property PACKAGE_PIN E17 [get_ports {B_2_1_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:215
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[1]' has been applied to the port object 'B_2_1_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[1]}]
set_property PACKAGE_PIN D18 [get_ports {B_2_1_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:216
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CEN[0]' has been applied to the port object 'B_2_1_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_2_1_CEN[0]}]

set_property PACKAGE_PIN K20 [get_ports B_2_1_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:218
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_WPN' has been applied to the port object 'B_2_1_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_1_WPN]
set_property PACKAGE_PIN H18 [get_ports B_2_1_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:219
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_ALE' has been applied to the port object 'B_2_1_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_1_ALE]
set_property PACKAGE_PIN G21 [get_ports B_2_1_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:220
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_CLE' has been applied to the port object 'B_2_1_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_1_CLE]
set_property PACKAGE_PIN J21 [get_ports B_2_1_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:221
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_2_1_WRN' has been applied to the port object 'B_2_1_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_2_1_WRN]


####################################################
# Bus 3 Pins
####################################################

# Bus 3_shared. For now name them B_3_0_*
set_property PACKAGE_PIN U25 [get_ports {B_SHARED_3_WEN_NCLK[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:229
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_3_WEN_NCLK[0]' has been applied to the port object 'B_SHARED_3_WEN_NCLK[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_3_WEN_NCLK[0]}]
set_property PACKAGE_PIN V26 [get_ports {B_SHARED_3_WEN_NCLK[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:230
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_3_WEN_NCLK[1]' has been applied to the port object 'B_SHARED_3_WEN_NCLK[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_3_WEN_NCLK[1]}]
set_property PACKAGE_PIN AB26 [get_ports {B_SHARED_3_WEN_NCLK[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:231
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_3_WEN_NCLK[2]' has been applied to the port object 'B_SHARED_3_WEN_NCLK[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_3_WEN_NCLK[2]}]
set_property PACKAGE_PIN W25 [get_ports {B_SHARED_3_WEN_NCLK[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:232
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_SHARED_3_WEN_NCLK[3]' has been applied to the port object 'B_SHARED_3_WEN_NCLK[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_SHARED_3_WEN_NCLK[3]}]

#Bus 3_0
set_property PACKAGE_PIN T20 [get_ports B_3_0_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:235
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQS' has been applied to the port object 'B_3_0_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_0_DQS]
set_property PACKAGE_PIN W19 [get_ports {B_3_0_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:236
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[7]' has been applied to the port object 'B_3_0_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[7]}]
set_property PACKAGE_PIN V19 [get_ports {B_3_0_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:237
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[6]' has been applied to the port object 'B_3_0_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[6]}]
set_property PACKAGE_PIN U19 [get_ports {B_3_0_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:238
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[5]' has been applied to the port object 'B_3_0_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[5]}]
set_property PACKAGE_PIN T19 [get_ports {B_3_0_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:239
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[4]' has been applied to the port object 'B_3_0_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[4]}]
set_property PACKAGE_PIN Y20 [get_ports {B_3_0_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:240
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[3]' has been applied to the port object 'B_3_0_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[3]}]
set_property PACKAGE_PIN W20 [get_ports {B_3_0_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:241
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[2]' has been applied to the port object 'B_3_0_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[2]}]
set_property PACKAGE_PIN Y21 [get_ports {B_3_0_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:242
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[1]' has been applied to the port object 'B_3_0_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[1]}]
set_property PACKAGE_PIN W21 [get_ports {B_3_0_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:243
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_6$nandPins_DQ[0]' has been applied to the port object 'B_3_0_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_DQ[0]}]

set_property PACKAGE_PIN AA25 [get_ports {B_3_0_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:245
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[7]' has been applied to the port object 'B_3_0_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[7]}]
set_property PACKAGE_PIN W24 [get_ports {B_3_0_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:246
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[6]' has been applied to the port object 'B_3_0_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[6]}]
set_property PACKAGE_PIN AB25 [get_ports {B_3_0_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:247
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[5]' has been applied to the port object 'B_3_0_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[5]}]
set_property PACKAGE_PIN AA23 [get_ports {B_3_0_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:248
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[4]' has been applied to the port object 'B_3_0_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[4]}]
set_property PACKAGE_PIN AC24 [get_ports {B_3_0_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:249
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[3]' has been applied to the port object 'B_3_0_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[3]}]
set_property PACKAGE_PIN W23 [get_ports {B_3_0_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:250
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[2]' has been applied to the port object 'B_3_0_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[2]}]
set_property PACKAGE_PIN Y23 [get_ports {B_3_0_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:251
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[1]' has been applied to the port object 'B_3_0_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[1]}]
set_property PACKAGE_PIN V22 [get_ports {B_3_0_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:252
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CEN[0]' has been applied to the port object 'B_3_0_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_0_CEN[0]}]

set_property PACKAGE_PIN AF22 [get_ports B_3_0_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:254
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_WPN' has been applied to the port object 'B_3_0_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_0_WPN]
set_property PACKAGE_PIN AD20 [get_ports B_3_0_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:255
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_ALE' has been applied to the port object 'B_3_0_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_0_ALE]
set_property PACKAGE_PIN AB21 [get_ports B_3_0_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:256
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_CLE' has been applied to the port object 'B_3_0_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_0_CLE]
set_property PACKAGE_PIN AA20 [get_ports B_3_0_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:257
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_0_WRN' has been applied to the port object 'B_3_0_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_0_WRN]

#Bus 3_1
set_property PACKAGE_PIN T17 [get_ports B_3_1_DQS]
# /home/mingliu/NandController/src/nand_phy.ucf:260
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQS' has been applied to the port object 'B_3_1_DQS'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_1_DQS]
set_property PACKAGE_PIN V16 [get_ports {B_3_1_DQ[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:261
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[7]' has been applied to the port object 'B_3_1_DQ[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[7]}]
set_property PACKAGE_PIN V14 [get_ports {B_3_1_DQ[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:262
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[6]' has been applied to the port object 'B_3_1_DQ[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[6]}]
set_property PACKAGE_PIN U14 [get_ports {B_3_1_DQ[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:263
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[5]' has been applied to the port object 'B_3_1_DQ[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[5]}]
set_property PACKAGE_PIN U16 [get_ports {B_3_1_DQ[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:264
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[4]' has been applied to the port object 'B_3_1_DQ[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[4]}]
set_property PACKAGE_PIN U15 [get_ports {B_3_1_DQ[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:265
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[3]' has been applied to the port object 'B_3_1_DQ[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[3]}]
set_property PACKAGE_PIN T15 [get_ports {B_3_1_DQ[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:266
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[2]' has been applied to the port object 'B_3_1_DQ[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[2]}]
set_property PACKAGE_PIN T14 [get_ports {B_3_1_DQ[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:267
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[1]' has been applied to the port object 'B_3_1_DQ[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[1]}]
set_property PACKAGE_PIN V18 [get_ports {B_3_1_DQ[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:268
# The conversion of 'IOSTANDARD' constraint on 'net' object 'busCtrl_7$nandPins_DQ[0]' has been applied to the port object 'B_3_1_DQ[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_DQ[0]}]

set_property PACKAGE_PIN Y25 [get_ports {B_3_1_CEN[7]}]
# /home/mingliu/NandController/src/nand_phy.ucf:270
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[7]' has been applied to the port object 'B_3_1_CEN[7]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[7]}]
set_property PACKAGE_PIN V24 [get_ports {B_3_1_CEN[6]}]
# /home/mingliu/NandController/src/nand_phy.ucf:271
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[6]' has been applied to the port object 'B_3_1_CEN[6]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[6]}]
set_property PACKAGE_PIN AA24 [get_ports {B_3_1_CEN[5]}]
# /home/mingliu/NandController/src/nand_phy.ucf:272
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[5]' has been applied to the port object 'B_3_1_CEN[5]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[5]}]
set_property PACKAGE_PIN AA22 [get_ports {B_3_1_CEN[4]}]
# /home/mingliu/NandController/src/nand_phy.ucf:273
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[4]' has been applied to the port object 'B_3_1_CEN[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[4]}]
set_property PACKAGE_PIN AB24 [get_ports {B_3_1_CEN[3]}]
# /home/mingliu/NandController/src/nand_phy.ucf:274
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[3]' has been applied to the port object 'B_3_1_CEN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[3]}]
set_property PACKAGE_PIN V23 [get_ports {B_3_1_CEN[2]}]
# /home/mingliu/NandController/src/nand_phy.ucf:275
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[2]' has been applied to the port object 'B_3_1_CEN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[2]}]
set_property PACKAGE_PIN Y22 [get_ports {B_3_1_CEN[1]}]
# /home/mingliu/NandController/src/nand_phy.ucf:276
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[1]' has been applied to the port object 'B_3_1_CEN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[1]}]
set_property PACKAGE_PIN U22 [get_ports {B_3_1_CEN[0]}]
# /home/mingliu/NandController/src/nand_phy.ucf:277
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CEN[0]' has been applied to the port object 'B_3_1_CEN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {B_3_1_CEN[0]}]

set_property PACKAGE_PIN AE22 [get_ports B_3_1_WPN]
# /home/mingliu/NandController/src/nand_phy.ucf:279
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_WPN' has been applied to the port object 'B_3_1_WPN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_1_WPN]
set_property PACKAGE_PIN AE20 [get_ports B_3_1_ALE]
# /home/mingliu/NandController/src/nand_phy.ucf:280
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_ALE' has been applied to the port object 'B_3_1_ALE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_1_ALE]
set_property PACKAGE_PIN AC21 [get_ports B_3_1_CLE]
# /home/mingliu/NandController/src/nand_phy.ucf:281
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_CLE' has been applied to the port object 'B_3_1_CLE'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_1_CLE]
set_property PACKAGE_PIN AB20 [get_ports B_3_1_WRN]
# /home/mingliu/NandController/src/nand_phy.ucf:282
# The conversion of 'IOSTANDARD' constraint on 'net' object 'B_3_1_WRN' has been applied to the port object 'B_3_1_WRN'.
set_property IOSTANDARD LVCMOS18 [get_ports B_3_1_WRN]













#
#
#NET "b1_dq[15]" LOC = AB6;
#NET "b1_dq[13]" LOC = Y8;
#NET "b1_dq[12]" LOC = AB5;
#NET "b1_dq[11]" LOC = AA5;
#
#NET "b1_cen[15]" LOC = W3;
#NET "b1_cen[14]" LOC = Y3;
#NET "b1_cen[13]" LOC = U7;
#NET "b1_cen[12]" LOC = V7;
#NET "b1_cen[11]" LOC = AB1;
#NET "b1_cen[10]" LOC = AC1;
#NET "b1_cen[9]" LOC = Y2;
#NET "b1_cen[8]" LOC = Y1;
#NET "b1_cen[7]" LOC = AD1;
#NET "b1_cen[6]" LOC = AE1;
#NET "b1_cen[5]" LOC = AE2;
#NET "b1_cen[4]" LOC = AF2;
#NET "b1_cen[3]" LOC = AB2;
#NET "b1_cen[2]" LOC = AC2;
#NET "b1_cen[1]" LOC = AA3;
#NET "b1_cen[0]" LOC = AA2;
#NET "b1_dq[10]" LOC = Y5;
#NET "b1_dq[9]" LOC = Y6;
#NET "b1_dq[7]" LOC = AD4;
#NET "b1_dq[6]" LOC = AC4;
#NET "b1_dq[5]" LOC = AF4;
#NET "b1_dq[4]" LOC = AF5;
#NET "b1_dq[3]" LOC = AF3;
#NET "b1_dq[2]" LOC = AE3;
#NET "b1_dq[1]" LOC = AD3;
#NET "b1_dq[14]" LOC = AA8;
#NET "b1_dqs[0]" LOC = AD5;
#NET "b1_dqs[1]" LOC = V8;
#NET "b2_dq[15]" LOC = D23;
#NET "b2_dq[14]" LOC = B24;
#NET "b2_dq[13]" LOC = C24;
#NET "b2_dq[12]" LOC = B26;
#NET "b2_dq[11]" LOC = C26;
#NET "b2_dq[10]" LOC = A25;
#NET "b2_dq[9]" LOC = B25;
#NET "b2_dq[8]" LOC = C22;
#NET "b2_dq[7]" LOC = D21;
#NET "b2_dq[6]" LOC = E21;
#NET "b2_dq[4]" LOC = B22;
#NET "b2_dq[3]" LOC = B21;
#NET "b2_dq[5]" LOC = A22;
#NET "b2_dq[2]" LOC = C21;
#NET "b2_dq[1]" LOC = D20;
#NET "b2_dq[0]" LOC = E20;
#NET "b2_dqs[1]" LOC = A23;
#NET "b2_dqs[0]" LOC = B20;
#
#NET "b1_dq[0]" LOC = AC3;
#NET "b1_dq[8]" LOC = Y7;
#
#NET "b2_cen[15]" LOC = G19;
#NET "b2_cen[14]" LOC = F20;
#NET "b2_cen[13]" LOC = H16;
#NET "b2_cen[12]" LOC = G16;
#NET "b2_cen[11]" LOC = C17;
#NET "b2_cen[10]" LOC = B17;
#NET "b2_cen[9]" LOC = E16;
#NET "b2_cen[8]" LOC = D16;
#NET "b2_cen[7]" LOC = A17;
#NET "b2_cen[6]" LOC = A18;
#NET "b2_cen[5]" LOC = B19;
#NET "b2_cen[4]" LOC = A19;
#NET "b2_cen[3]" LOC = E17;
#NET "b2_cen[2]" LOC = E18;
#NET "b2_cen[1]" LOC = D18;
#NET "b2_cen[0]" LOC = C18;
#NET "b2_rb[15]" LOC = K15;
#NET "b2_rb[14]" LOC = J16;
#NET "b2_rb[13]" LOC = J14;
#NET "b2_rb[12]" LOC = J15;
#NET "b2_rb[11]" LOC = K16;
#NET "b2_rb[10]" LOC = K17;
#NET "b2_rb[9]" LOC = M14;
#NET "b2_rb[8]" LOC = L14;
#NET "b2_rb[7]" LOC = M15;
#NET "b2_rb[6]" LOC = L15;
#NET "b2_rb[5]" LOC = M16;
#NET "b2_rb[4]" LOC = M17;
#NET "b2_rb[3]" LOC = J19;
#NET "b2_rb[2]" LOC = H19;
#NET "b2_rb[1]" LOC = L17;
#NET "b2_rb[0]" LOC = L18;
#
#NET "b3_dq[15]" LOC = V16;
#NET "b3_dq[14]" LOC = V14;
#NET "b3_dq[13]" LOC = U14;
#NET "b3_dq[12]" LOC = U16;
#NET "b3_dq[11]" LOC = U15;
#NET "b3_dq[10]" LOC = T15;
#NET "b3_dq[9]" LOC = T14;
#NET "b3_dq[8]" LOC = V18;
#NET "b3_dq[7]" LOC = W19;
#NET "b3_dq[6]" LOC = V19;
#NET "b3_dq[5]" LOC = U19;
#NET "b3_dq[4]" LOC = T19;
#NET "b3_dq[3]" LOC = Y20;
#NET "b3_dq[2]" LOC = W20;
#NET "b3_dq[1]" LOC = Y21;
#NET "b3_dq[0]" LOC = W21;
#NET "b3_dqs[1]" LOC = T17;
#NET "b3_dqs[0]" LOC = T20;
#
#NET "b3_cen[15]" LOC = Y25;
#NET "b3_cen[14]" LOC = AA25;
#NET "b3_cen[13]" LOC = V24;
#NET "b3_cen[12]" LOC = W24;
#NET "b3_cen[11]" LOC = AA24;
#NET "b3_cen[10]" LOC = AB25;
#NET "b3_cen[9]" LOC = AA22;
#NET "b3_cen[8]" LOC = AA23;
#NET "b3_cen[7]" LOC = AB24;
#NET "b3_cen[6]" LOC = AC24;
#NET "b3_cen[5]" LOC = V23;
#NET "b3_cen[4]" LOC = W23;
#NET "b3_cen[3]" LOC = Y22;
#NET "b3_cen[2]" LOC = Y23;
#NET "b3_cen[1]" LOC = U22;
#NET "b3_cen[0]" LOC = V22;
#NET "b3_rb[15]" LOC = AE25;
#NET "b3_rb[14]" LOC = AE26;
#NET "b3_rb[13]" LOC = AC22;
#NET "b3_rb[12]" LOC = AC23;
#NET "b3_rb[11]" LOC = AF24;
#NET "b3_rb[10]" LOC = AF25;
#NET "b3_rb[9]" LOC = AD25;
#NET "b3_rb[8]" LOC = AD26;
#NET "b3_rb[7]" LOC = AE23;
#NET "b3_rb[6]" LOC = AF23;
#NET "b3_rb[5]" LOC = AD23;
#NET "b3_rb[4]" LOC = AD24;
#NET "b3_rb[3]" LOC = AD21;
#NET "b3_rb[2]" LOC = AE21;
#NET "b3_rb[1]" LOC = AF19;
#NET "b3_rb[0]" LOC = AF20;
#
#
#
#NET "b1_rb[15]" LOC = R3;
#NET "b1_rb[14]" LOC = P3;
#NET "b1_rb[13]" LOC = P4;
#NET "b1_rb[12]" LOC = N4;
#NET "b1_rb[11]" LOC = R1;
#NET "b1_rb[10]" LOC = P1;
#NET "b1_rb[9]" LOC = T4;
#NET "b1_rb[8]" LOC = T3;
#NET "b1_rb[7]" LOC = T2;
#NET "b1_rb[6]" LOC = R2;
#NET "b1_rb[5]" LOC = U2;
#NET "b1_rb[4]" LOC = U1;
#NET "b1_rb[3]" LOC = P6;
#NET "b1_rb[2]" LOC = P5;
#NET "b1_rb[1]" LOC = T5;
#NET "b1_rb[0]" LOC = R5;
#
#NET "b1_sys_clk_n" LOC = AB4;
#NET "b1_sys_clk_p" LOC = AA4;
#
#
#NET "b3_sys_clk_n" LOC = V21;
#NET "b3_sys_clk_p" LOC = U21;
#NET "b2_sys_clk_n" LOC = C19;
#NET "b2_sys_clk_p" LOC = D19;
#
#NET "b1_nand_clk" LOC = V3;
#NET "b2_nand_clk" LOC = F18;
#NET "b3_nand_clk" LOC = AB26;
#
#NET "b1_wpn[1]" LOC = U6;
#NET "b1_wpn[0]" LOC = U5;
#NET "b2_wpn[1]" LOC = K20;
#NET "b2_wpn[0]" LOC = J20;
#NET "b3_wpn[1]" LOC = AE22;
#NET "b3_wpn[0]" LOC = AF22;

#
#
##NET "ox_a7_scl" LOC = L24;
##NET "ox_a7_sda" LOC = M24;
##NET "ox_a7_oe" LOC = M25;
##NET "ox_fmc_scl" LOC = N23;
##NET "ox_fmc_sda" LOC = P19;
##NET "ox_fmc_oe" LOC = N19;
#
## PlanAhead Generated physical constraints 
#
#
#NET "b1_nand_clk0" LOC = V1;
#NET "b1_nand_clk1" LOC = W5;
#NET "b1_nand_clk2" LOC = V3;
#NET "b1_nand_clk3" LOC = V6;
#
#NET "b1_ale[0]" LOC = R8;
#NET "b1_ale[1]" LOC = P8;
#NET "b1_cle[0]" LOC = R7;
#NET "b1_cle[1]" LOC = R6;
#NET "b1_wrn[0]" LOC = T8;
#NET "b1_wrn[1]" LOC = T7;
#NET "b3_nand_clk0" LOC = U25;
#NET "b3_nand_clk1" LOC = V26;
#NET "b3_nand_clk2" LOC = AB26;
#NET "b3_nand_clk3" LOC = W25;
#NET "b3_ale[0]" LOC = AD20;
#NET "b3_ale[1]" LOC = AE20;
#NET "b3_cle[0]" LOC = AB21;
#NET "b3_cle[1]" LOC = AC21;
#NET "b3_wrn[0]" LOC = AA20;
#NET "b3_wrn[1]" LOC = AB20;
#NET "ox_fmc_intr" LOC = N19;
#NET "b2_nand_clk0" LOC = H14;
#NET "b2_nand_clk1" LOC = G17;
#NET "b2_nand_clk2" LOC = F18;
#NET "b2_nand_clk3" LOC = G15;
#NET "b2_ale[0]" LOC = J18;
#NET "b2_ale[1]" LOC = H18;
#NET "b2_cle[0]" LOC = G20;
#NET "b2_cle[1]" LOC = G21;
#NET "b2_wrn[0]" LOC = K21;
#NET "b2_wrn[1]" LOC = J21;

