
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'nand_phy.ucf'
####################################################################################

#Anomalies in pin assignment
# Each CHIP has shared WE#/NAND_CLK (probably a bad choice but too late)
# For CE#, [0, 2, 4, 6..] on the schematic correponds to Bus_N_0
# CE#, [1, 3, 5, 7..] on the schematic correponds to Bus_N_1


####################################################
#Clock in and reset
####################################################
set_property PACKAGE_PIN E5 [get_ports CLK_sysClkP]
# /home/mingliu/NandController/src/nand_phy.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK_sysClkP' has been applied to the port object 'CLK_sysClkP'.
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkP]
set_property PACKAGE_PIN D5 [get_ports CLK_sysClkN]
# /home/mingliu/NandController/src/nand_phy.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK_sysClkN' has been applied to the port object 'CLK_sysClkN'.
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkN]
#set_property PACKAGE_PIN P14 [get_ports RST_N_sysRstn]
# /home/mingliu/NandController/src/nand_phy.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RST_N_sysRstn' has been applied to the port object 'RST_N_sysRstn'.
#set_property IOSTANDARD LVCMOS18 [get_ports RST_N_sysRstn]


#Clock constraint

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# /home/mingliu/NandController/src/nand_phy.ucf:20
create_clock -name CLK_sysClkP -period 10.000 [get_ports CLK_sysClkP]
set_input_jitter CLK_sysClkP 0.100


